# Generated by Django 3.2.8 on 2021-11-05 12:06

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('movies', '0005_auto_20211104_1001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
            ],
            options={
                'ordering': ('first_name',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
